# Generated by Django 2.2.5 on 2019-09-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('idtask', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('datedeadline', models.DateTimeField(blank=True, null=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
